import { definePrefab } from '@core/lib/serialization/assets/definePrefabs';

export default definePrefab({
  id: 'black_knight',
  name: 'black_knight',
  root: {
    name: 'black_knight',
    components: {
      PersistentId: {
        id: 'c60a6b6c-b059-4359-92b6-9118cb67437b',
      },
    },
    children: [
      {
        name: 'knight_base',
        components: {
          PersistentId: {
            id: 'bd6c0fd1-9724-4d6d-945a-3052e9ac97a1',
          },
          Transform: {
            position: [0, 0, 0],
            rotation: [0, 0, 0],
            scale: [0.7, 0.3, 0.7],
          },
          MeshRenderer: {
            meshId: 'cylinder',
            materialId: 'default',
            enabled: true,
            castShadows: true,
            receiveShadows: true,
            modelPath: '',
            material: {
              shader: 'standard',
              materialType: 'solid',
              color: '#2c2c2c',
              metalness: 0.2,
              roughness: 0.7,
              emissive: '#000000',
              emissiveIntensity: 0,
              normalScale: 1,
              occlusionStrength: 1,
              textureOffsetX: 0,
              textureOffsetY: 0,
              textureRepeatX: 1,
              textureRepeatY: 1,
              albedoTexture: '',
              normalTexture: '',
              metallicTexture: '',
              roughnessTexture: '',
              emissiveTexture: '',
              occlusionTexture: '',
            },
          },
        },
      },
      {
        name: 'knight_body',
        components: {
          PersistentId: {
            id: 'b0008f62-0441-4741-872b-a6d0907dc73f',
          },
          Transform: {
            position: [0, 0.7, 0],
            rotation: [0, 0, 0],
            scale: [0.5, 0.7, 0.4],
          },
          MeshRenderer: {
            meshId: 'cube',
            materialId: 'default',
            enabled: true,
            castShadows: true,
            receiveShadows: true,
            modelPath: '',
            material: {
              shader: 'standard',
              materialType: 'solid',
              color: '#2c2c2c',
              metalness: 0.2,
              roughness: 0.7,
              emissive: '#000000',
              emissiveIntensity: 0,
              normalScale: 1,
              occlusionStrength: 1,
              textureOffsetX: 0,
              textureOffsetY: 0,
              textureRepeatX: 1,
              textureRepeatY: 1,
              albedoTexture: '',
              normalTexture: '',
              metallicTexture: '',
              roughnessTexture: '',
              emissiveTexture: '',
              occlusionTexture: '',
            },
          },
        },
      },
      {
        name: 'knight_head_main',
        components: {
          PersistentId: {
            id: 'eed2f90e-e3b8-4f92-9e25-9ead532b1800',
          },
          Transform: {
            position: [0, 1.2, 0.1],
            rotation: [0, 0, 0],
            scale: [0.4, 0.4, 0.3],
          },
          MeshRenderer: {
            meshId: 'cube',
            materialId: 'default',
            enabled: true,
            castShadows: true,
            receiveShadows: true,
            modelPath: '',
            material: {
              shader: 'standard',
              materialType: 'solid',
              color: '#2c2c2c',
              metalness: 0.2,
              roughness: 0.7,
              emissive: '#000000',
              emissiveIntensity: 0,
              normalScale: 1,
              occlusionStrength: 1,
              textureOffsetX: 0,
              textureOffsetY: 0,
              textureRepeatX: 1,
              textureRepeatY: 1,
              albedoTexture: '',
              normalTexture: '',
              metallicTexture: '',
              roughnessTexture: '',
              emissiveTexture: '',
              occlusionTexture: '',
            },
          },
        },
      },
      {
        name: 'knight_ear',
        components: {
          PersistentId: {
            id: 'ef8821a6-d870-469d-8046-b4aef1833b85',
          },
          Transform: {
            position: [-0.1, 1.5, 0.1],
            rotation: [0, 0, 0],
            scale: [0.08, 0.3, 0.08],
          },
          MeshRenderer: {
            meshId: 'cone',
            materialId: 'default',
            enabled: true,
            castShadows: true,
            receiveShadows: true,
            modelPath: '',
            material: {
              shader: 'standard',
              materialType: 'solid',
              color: '#2c2c2c',
              metalness: 0.2,
              roughness: 0.7,
              emissive: '#000000',
              emissiveIntensity: 0,
              normalScale: 1,
              occlusionStrength: 1,
              textureOffsetX: 0,
              textureOffsetY: 0,
              textureRepeatX: 1,
              textureRepeatY: 1,
              albedoTexture: '',
              normalTexture: '',
              metallicTexture: '',
              roughnessTexture: '',
              emissiveTexture: '',
              occlusionTexture: '',
            },
          },
        },
      },
      {
        name: 'knight_snout',
        components: {
          PersistentId: {
            id: '75e5739e-f122-49a6-846e-5300de028c3f',
          },
          Transform: {
            position: [0.2, 1.3, 0.1],
            rotation: [0, 0, 0],
            scale: [0.2, 0.15, 0.15],
          },
          MeshRenderer: {
            meshId: 'cube',
            materialId: 'default',
            enabled: true,
            castShadows: true,
            receiveShadows: true,
            modelPath: '',
            material: {
              shader: 'standard',
              materialType: 'solid',
              color: '#2c2c2c',
              metalness: 0.2,
              roughness: 0.7,
              emissive: '#000000',
              emissiveIntensity: 0,
              normalScale: 1,
              occlusionStrength: 1,
              textureOffsetX: 0,
              textureOffsetY: 0,
              textureRepeatX: 1,
              textureRepeatY: 1,
              albedoTexture: '',
              normalTexture: '',
              metallicTexture: '',
              roughnessTexture: '',
              emissiveTexture: '',
              occlusionTexture: '',
            },
          },
        },
      },
    ],
  },
  metadata: {
    createdAt: '2025-11-16T09:42:58.502Z',
    createdFrom: 154,
  },
  dependencies: ['default'],
});
