import { definePrefab } from '@core/lib/serialization/assets/definePrefabs';

export default definePrefab({
  id: 'black_queen',
  name: 'black_queen',
  root: {
    name: 'black_queen',
    components: {
      PersistentId: {
        id: '0747146c-3a1c-4c0d-8581-0dbe87a4ac62',
      },
    },
    children: [
      {
        name: 'queen_base',
        components: {
          PersistentId: {
            id: '08b14fe5-3cc8-4f07-864c-5945c8d321dd',
          },
          Transform: {
            position: [0, 0, 0],
            rotation: [0, 0, 0],
            scale: [0.8, 0.3, 0.8],
          },
          MeshRenderer: {
            meshId: 'cylinder',
            materialId: 'default',
            enabled: true,
            castShadows: true,
            receiveShadows: true,
            modelPath: '',
            material: {
              shader: 'standard',
              materialType: 'solid',
              color: '#2c2c2c',
              metalness: 0.2,
              roughness: 0.7,
              emissive: '#000000',
              emissiveIntensity: 0,
              normalScale: 1,
              occlusionStrength: 1,
              textureOffsetX: 0,
              textureOffsetY: 0,
              textureRepeatX: 1,
              textureRepeatY: 1,
              albedoTexture: '',
              normalTexture: '',
              metallicTexture: '',
              roughnessTexture: '',
              emissiveTexture: '',
              occlusionTexture: '',
            },
          },
        },
      },
      {
        name: 'queen_body',
        components: {
          PersistentId: {
            id: '3d98d9e1-5d33-44d8-ba01-bdc175091e67',
          },
          Transform: {
            position: [0, 0.6, 0],
            rotation: [0, 0, 0],
            scale: [0.6, 0.7, 0.6],
          },
          MeshRenderer: {
            meshId: 'cylinder',
            materialId: 'default',
            enabled: true,
            castShadows: true,
            receiveShadows: true,
            modelPath: '',
            material: {
              shader: 'standard',
              materialType: 'solid',
              color: '#2c2c2c',
              metalness: 0.2,
              roughness: 0.7,
              emissive: '#000000',
              emissiveIntensity: 0,
              normalScale: 1,
              occlusionStrength: 1,
              textureOffsetX: 0,
              textureOffsetY: 0,
              textureRepeatX: 1,
              textureRepeatY: 1,
              albedoTexture: '',
              normalTexture: '',
              metallicTexture: '',
              roughnessTexture: '',
              emissiveTexture: '',
              occlusionTexture: '',
            },
          },
        },
      },
      {
        name: 'queen_head',
        components: {
          PersistentId: {
            id: 'faec256b-edd1-4c02-92ac-89b1d4c633fc',
          },
          Transform: {
            position: [0, 1.1, 0],
            rotation: [0, 0, 0],
            scale: [0.4, 0.4, 0.4],
          },
          MeshRenderer: {
            meshId: 'sphere',
            materialId: 'default',
            enabled: true,
            castShadows: true,
            receiveShadows: true,
            modelPath: '',
            material: {
              shader: 'standard',
              materialType: 'solid',
              color: '#2c2c2c',
              metalness: 0.2,
              roughness: 0.7,
              emissive: '#000000',
              emissiveIntensity: 0,
              normalScale: 1,
              occlusionStrength: 1,
              textureOffsetX: 0,
              textureOffsetY: 0,
              textureRepeatX: 1,
              textureRepeatY: 1,
              albedoTexture: '',
              normalTexture: '',
              metallicTexture: '',
              roughnessTexture: '',
              emissiveTexture: '',
              occlusionTexture: '',
            },
          },
        },
      },
      {
        name: 'queen_crown',
        components: {
          PersistentId: {
            id: '17f97715-58af-4d9a-988e-de317a674737',
          },
          Transform: {
            position: [0, 1.4, 0],
            rotation: [0, 0, 0],
            scale: [0.35, 0.3, 0.35],
          },
          MeshRenderer: {
            meshId: 'cone',
            materialId: 'default',
            enabled: true,
            castShadows: true,
            receiveShadows: true,
            modelPath: '',
            material: {
              shader: 'standard',
              materialType: 'solid',
              color: '#2c2c2c',
              metalness: 0.2,
              roughness: 0.7,
              emissive: '#000000',
              emissiveIntensity: 0,
              normalScale: 1,
              occlusionStrength: 1,
              textureOffsetX: 0,
              textureOffsetY: 0,
              textureRepeatX: 1,
              textureRepeatY: 1,
              albedoTexture: '',
              normalTexture: '',
              metallicTexture: '',
              roughnessTexture: '',
              emissiveTexture: '',
              occlusionTexture: '',
            },
          },
        },
      },
      {
        name: 'queen_crown_ball',
        components: {
          PersistentId: {
            id: '2859ab7c-c097-4d7b-ae36-0a2481642ee2',
          },
          Transform: {
            position: [0, 1.6, 0],
            rotation: [0, 0, 0],
            scale: [0.1, 0.1, 0.1],
          },
          MeshRenderer: {
            meshId: 'sphere',
            materialId: 'default',
            enabled: true,
            castShadows: true,
            receiveShadows: true,
            modelPath: '',
            material: {
              shader: 'standard',
              materialType: 'solid',
              color: '#2c2c2c',
              metalness: 0.2,
              roughness: 0.7,
              emissive: '#000000',
              emissiveIntensity: 0,
              normalScale: 1,
              occlusionStrength: 1,
              textureOffsetX: 0,
              textureOffsetY: 0,
              textureRepeatX: 1,
              textureRepeatY: 1,
              albedoTexture: '',
              normalTexture: '',
              metallicTexture: '',
              roughnessTexture: '',
              emissiveTexture: '',
              occlusionTexture: '',
            },
          },
        },
      },
    ],
  },
  metadata: {
    createdAt: '2025-11-16T09:43:11.039Z',
    createdFrom: 166,
  },
  dependencies: ['default'],
});
