import { definePrefab } from '@core/lib/serialization/assets/definePrefabs';

export default definePrefab({
  id: 'white_king',
  name: 'white_king',
  root: {
    name: 'white_king',
    components: {
      PersistentId: {
        id: '1635703f-918e-450d-9cf2-fba63c7e9499',
      },
    },
    children: [
      {
        name: 'king_base',
        components: {
          PersistentId: {
            id: '91b4df5e-3904-4b84-a53c-a510043f39d6',
          },
          Transform: {
            position: [0, 0, 0],
            rotation: [0, 0, 0],
            scale: [0.8, 0.3, 0.8],
          },
          MeshRenderer: {
            meshId: 'cylinder',
            materialId: 'default',
            enabled: true,
            castShadows: true,
            receiveShadows: true,
            modelPath: '',
            material: {
              shader: 'standard',
              materialType: 'solid',
              color: '#f0f0f0',
              metalness: 0.1,
              roughness: 0.8,
              emissive: '#000000',
              emissiveIntensity: 0,
              normalScale: 1,
              occlusionStrength: 1,
              textureOffsetX: 0,
              textureOffsetY: 0,
              textureRepeatX: 1,
              textureRepeatY: 1,
              albedoTexture: '',
              normalTexture: '',
              metallicTexture: '',
              roughnessTexture: '',
              emissiveTexture: '',
              occlusionTexture: '',
            },
          },
        },
      },
      {
        name: 'king_body',
        components: {
          PersistentId: {
            id: 'e1862e6b-9298-4953-b35c-b340c3d28372',
          },
          Transform: {
            position: [0, 0.6, 0],
            rotation: [0, 0, 0],
            scale: [0.6, 0.8, 0.6],
          },
          MeshRenderer: {
            meshId: 'cylinder',
            materialId: 'default',
            enabled: true,
            castShadows: true,
            receiveShadows: true,
            modelPath: '',
            material: {
              shader: 'standard',
              materialType: 'solid',
              color: '#f0f0f0',
              metalness: 0.1,
              roughness: 0.8,
              emissive: '#000000',
              emissiveIntensity: 0,
              normalScale: 1,
              occlusionStrength: 1,
              textureOffsetX: 0,
              textureOffsetY: 0,
              textureRepeatX: 1,
              textureRepeatY: 1,
              albedoTexture: '',
              normalTexture: '',
              metallicTexture: '',
              roughnessTexture: '',
              emissiveTexture: '',
              occlusionTexture: '',
            },
          },
        },
      },
      {
        name: 'king_head',
        components: {
          PersistentId: {
            id: 'e12ed23b-cf64-4dbe-bf8f-74dc3670c6cb',
          },
          Transform: {
            position: [0, 1.2, 0],
            rotation: [0, 0, 0],
            scale: [0.4, 0.4, 0.4],
          },
          MeshRenderer: {
            meshId: 'sphere',
            materialId: 'default',
            enabled: true,
            castShadows: true,
            receiveShadows: true,
            modelPath: '',
            material: {
              shader: 'standard',
              materialType: 'solid',
              color: '#f0f0f0',
              metalness: 0.1,
              roughness: 0.8,
              emissive: '#000000',
              emissiveIntensity: 0,
              normalScale: 1,
              occlusionStrength: 1,
              textureOffsetX: 0,
              textureOffsetY: 0,
              textureRepeatX: 1,
              textureRepeatY: 1,
              albedoTexture: '',
              normalTexture: '',
              metallicTexture: '',
              roughnessTexture: '',
              emissiveTexture: '',
              occlusionTexture: '',
            },
          },
        },
      },
      {
        name: 'king_cross_vertical',
        components: {
          PersistentId: {
            id: 'bdefc2cc-f2d2-4217-be4c-ce32a119b572',
          },
          Transform: {
            position: [0, 1.6, 0],
            rotation: [0, 0, 0],
            scale: [0.08, 0.4, 0.08],
          },
          MeshRenderer: {
            meshId: 'cylinder',
            materialId: 'default',
            enabled: true,
            castShadows: true,
            receiveShadows: true,
            modelPath: '',
            material: {
              shader: 'standard',
              materialType: 'solid',
              color: '#f0f0f0',
              metalness: 0.1,
              roughness: 0.8,
              emissive: '#000000',
              emissiveIntensity: 0,
              normalScale: 1,
              occlusionStrength: 1,
              textureOffsetX: 0,
              textureOffsetY: 0,
              textureRepeatX: 1,
              textureRepeatY: 1,
              albedoTexture: '',
              normalTexture: '',
              metallicTexture: '',
              roughnessTexture: '',
              emissiveTexture: '',
              occlusionTexture: '',
            },
          },
        },
      },
      {
        name: 'king_cross_horizontal',
        components: {
          PersistentId: {
            id: '546959ac-9175-4d3a-ab39-346f6b8c9b43',
          },
          Transform: {
            position: [0, 1.7, 0],
            rotation: [0, 0, 0],
            scale: [0.25, 0.08, 0.08],
          },
          MeshRenderer: {
            meshId: 'cylinder',
            materialId: 'default',
            enabled: true,
            castShadows: true,
            receiveShadows: true,
            modelPath: '',
            material: {
              shader: 'standard',
              materialType: 'solid',
              color: '#f0f0f0',
              metalness: 0.1,
              roughness: 0.8,
              emissive: '#000000',
              emissiveIntensity: 0,
              normalScale: 1,
              occlusionStrength: 1,
              textureOffsetX: 0,
              textureOffsetY: 0,
              textureRepeatX: 1,
              textureRepeatY: 1,
              albedoTexture: '',
              normalTexture: '',
              metallicTexture: '',
              roughnessTexture: '',
              emissiveTexture: '',
              occlusionTexture: '',
            },
          },
        },
      },
    ],
  },
  metadata: {
    createdAt: '2025-11-16T09:43:15.775Z',
    createdFrom: 172,
  },
  dependencies: ['default'],
});
