import type { IMaterialDefinition } from '@/core/materials/Material.types';

export interface IMaterialTemplate {
  id: string;
  name: string;
  shader: 'standard' | 'unlit';
  materialType: 'solid' | 'texture';
  description: string;
  previewMaterial: IMaterialDefinition;
}

export const MATERIAL_TEMPLATES: IMaterialTemplate[] = [
  {
    id: 'plastic',
    name: 'Plastic',
    shader: 'standard' as const,
    materialType: 'solid' as const,
    description: 'Smooth plastic material',
    previewMaterial: {
      id: 'preview_plastic',
      name: 'Plastic Preview',
      shader: 'standard' as const,
      materialType: 'solid' as const,
      color: '#4a90e2',
      metalness: 0.0,
      roughness: 0.2,
      emissive: '#000000',
      emissiveIntensity: 0,
      normalScale: 1,
      occlusionStrength: 1,
      textureOffsetX: 0,
      textureOffsetY: 0,
    } as IMaterialDefinition,
  },
  {
    id: 'metal',
    name: 'Metal',
    shader: 'standard' as const,
    materialType: 'solid' as const,
    description: 'Metallic material with high reflectance',
    previewMaterial: {
      id: 'preview_metal',
      name: 'Metal Preview',
      shader: 'standard' as const,
      materialType: 'solid' as const,
      color: '#888888',
      metalness: 1.0,
      roughness: 0.1,
      emissive: '#000000',
      emissiveIntensity: 0,
      normalScale: 1,
      occlusionStrength: 1,
      textureOffsetX: 0,
      textureOffsetY: 0,
    } as IMaterialDefinition,
  },
  {
    id: 'glass',
    name: 'Glass',
    shader: 'standard' as const,
    materialType: 'solid' as const,
    description: 'Transparent glass-like material',
    previewMaterial: {
      id: 'preview_glass',
      name: 'Glass Preview',
      shader: 'standard' as const,
      materialType: 'solid' as const,
      color: '#ffffff',
      metalness: 0.0,
      roughness: 0.05,
      emissive: '#000000',
      emissiveIntensity: 0,
      normalScale: 1,
      occlusionStrength: 1,
      textureOffsetX: 0,
      textureOffsetY: 0,
    } as IMaterialDefinition,
  },
  {
    id: 'emissive',
    name: 'Emissive',
    shader: 'standard' as const,
    materialType: 'solid' as const,
    description: 'Glowing emissive material',
    previewMaterial: {
      id: 'preview_emissive',
      name: 'Emissive Preview',
      shader: 'standard' as const,
      materialType: 'solid' as const,
      color: '#ffffff',
      metalness: 0.0,
      roughness: 0.5,
      emissive: '#00ff88',
      emissiveIntensity: 1.5,
      normalScale: 1,
      occlusionStrength: 1,
      textureOffsetX: 0,
      textureOffsetY: 0,
    } as IMaterialDefinition,
  },
  {
    id: 'rubber',
    name: 'Rubber',
    shader: 'standard' as const,
    materialType: 'solid' as const,
    description: 'Matte rubber material',
    previewMaterial: {
      id: 'preview_rubber',
      name: 'Rubber Preview',
      shader: 'standard' as const,
      materialType: 'solid' as const,
      color: '#2c2c2c',
      metalness: 0.0,
      roughness: 0.9,
      emissive: '#000000',
      emissiveIntensity: 0,
      normalScale: 1,
      occlusionStrength: 1,
      textureOffsetX: 0,
      textureOffsetY: 0,
    } as IMaterialDefinition,
  },
  {
    id: 'fabric',
    name: 'Fabric',
    shader: 'standard' as const,
    materialType: 'texture' as const,
    description: 'Textured fabric material',
    previewMaterial: {
      id: 'preview_fabric',
      name: 'Fabric Preview',
      shader: 'standard' as const,
      materialType: 'texture' as const,
      color: '#8b4513',
      metalness: 0.0,
      roughness: 0.8,
      emissive: '#000000',
      emissiveIntensity: 0,
      normalScale: 1,
      occlusionStrength: 1,
      textureOffsetX: 0,
      textureOffsetY: 0,
    } as IMaterialDefinition,
  },
  {
    id: 'wood',
    name: 'Wood',
    shader: 'standard' as const,
    materialType: 'texture' as const,
    description: 'Natural wood material',
    previewMaterial: {
      id: 'preview_wood',
      name: 'Wood Preview',
      shader: 'standard' as const,
      materialType: 'texture' as const,
      color: '#8b4513',
      metalness: 0.0,
      roughness: 0.7,
      emissive: '#000000',
      emissiveIntensity: 0,
      normalScale: 1,
      occlusionStrength: 1,
      textureOffsetX: 0,
      textureOffsetY: 0,
    } as IMaterialDefinition,
  },
  {
    id: 'unlit_flat',
    name: 'Flat Color',
    shader: 'unlit' as const,
    materialType: 'solid' as const,
    description: 'Flat unlit color for UI elements',
    previewMaterial: {
      id: 'preview_unlit_flat',
      name: 'Flat Color Preview',
      shader: 'unlit' as const,
      materialType: 'solid' as const,
      color: '#ff6b6b',
      metalness: 0,
      roughness: 1,
      emissive: '#000000',
      emissiveIntensity: 0,
      normalScale: 1,
      occlusionStrength: 1,
      textureOffsetX: 0,
      textureOffsetY: 0,
    } as IMaterialDefinition,
  },
];